---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook
rules:
  - apiGroups: ["test.deckhouse.io"]
    resources: ["webhookrequests"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webhook
subjects:
  - kind: ServiceAccount
    name: webhook
